### ISSUE TITLE
API Request isn't updating

### ISSUE THREAD

**Issue by admills** [reaktivstudios/gppro-google-webfonts#6]
After checking across multiple themes which we support, it looks like the Google Fonts API request isn't being updated as expected when using the Google Web Fonts plugin.

### The Issue
In DPP, in the Design tab, a font will be updated and the preview will show the updated font. But, when the Save button is pressed, the font is NOT loaded and a fallback font (serif, san-serif, cursive) is loaded instead.

### Important Note:
It is possible to get a false positive which makes it look like the plugin is working. If you test with a font which your computer has installed/enabled, then your computer may display the font, even though the browser isn't loading the font.

### Fix
Looking at the source code, fonts.googleapis.com is loaded, but the [Google Fonts Developer API recommends using the following format for the request](https://developers.google.com/fonts/docs/developer_api#a_quick_example): 
https://www.googleapis.com/webfonts/v1/webfonts?key=YOUR-API-KEY

The link is never updated to reflect the chosen fonts. However, testing the current release against v1.0.8, the previous version was updating as expected.

**Comment by admills** [comment]
I dug a little deeper into this. If you attempt to use the plugin without the Google Fonts API, there is a limited set of fonts which come up initially. **Those fonts aren't loading at all** - whether using the API or not. However, if the API is added to Settings, then all fonts other than that list will work as expected.

**Comment by admills** [comment]
Here is the full list of fonts which won't load via Google Fonts:

SANS SERIF
Abel
Archivo Narrow
Cabin
Dosis
Gill Sans
Helvetica
Impact
Inder
Josefin Sans
Lato
Lucida Grande
Montserrat
Noto Sans
Open Sans
Open Sans Condensed
Orienta
Oswald
Oxygen
Pathway Gothic One
PT Sans
Quattrocento Sans
Quicksand
Raleway
Roboto
Roboto Condensed
Signika
Source Sans Pro
Syncopate
Trebuchet
Verdana

SERIF
Abril Fatface
Arvo
Baskerville
Big Caslon
Bitter
Bree Serif
Crimson Text
Enriqueta
Fenix
Garamond
Hoefler Text
Josefin Slab
Lora
Lucida Bright
Merriweather
Neuton
Nixie One
Noto Serif
Old Standard TT
Palatino
Playfair Display
Podkova
PT Serif
Quattrocento
Roboto Slab
Rokkitt
Source Serif Pro
Vollkorn

CURSIVE
Arizonia
Bilbo Swash Caps
Cabin Sketch
Calligraffitti
Dancing Script
Fredericka the Great
Great Vibes
Handlee
Kaushan Script
Londrina Outline
Londrina Sketch
Meddon
Pacifico
Rock Salt
Sacramento
Sofia

MONOSPACE
Droid Sans Mono
Monospace
Source Code Pro
Ubuntu Mono

**Comment by corywebb** [comment]
Just a quick note here... the API URL is correct in the code. See https://github.com/reaktivstudios/gppro-google-webfonts/blob/master/lib/class-google.php#L136

Where it loads the font on the front end, it uses `//fonts.googleapis.com/css?family=`, which is correct.

I'm looking into the other issues listed.

**Comment by admills** [comment]
Fixed with v2.0.1 release.
