### ISSUE TITLE
Unable to remove selected fonts

### ISSUE THREAD

**Issue by admills** [reaktivstudios/gppro-google-webfonts#9]
### The Issue
In the **Fonts** tab, it is possible to click the "**+**" icon next to a font name to add that font to the **Selected Fonts** section in the sidebar. Doing so, will make those fonts the available fonts from within the **Design** tab, when customizing a font-family setting. 

However, if you add fonts to the **Selected Fonts** section, leave the **Fonts** tab, and then go back to the **Fonts** tab later, the **Selected Fonts** section will now be empty. 

The fonts which had been selected will remain as the only available fonts within the Design tab, when customizing a font-family setting. There is no way to remove those fonts from the Select Fonts section, as that section remains blank. More fonts can be added to that section, but no fonts can be removed.

### Note
A valid Google Fonts API was in place during the testing.

**Comment by corywebb** [comment]
I have a fix for this in this PR: https://github.com/reaktivstudios/genesis-design-pro/pull/562

**Comment by admills** [comment]
Merged https://github.com/reaktivstudios/genesis-design-pro/pull/562
